### PR TITLE
Fix up FE_FaceQ::hp_*_dof_identities

### PR DESCRIPTION
**Pull request by masterleinad**
Since my comment in the Google Groups discussion was a bit misleading, I took the freedom to fix up the remaining parts. 
Feel free to modify as you wish! In particular, you may want to replace "Simfeld" by your real name in `doc/news/changes/minor/20170711Simfeld-DanielArndt` to take credit.

### CODE REVIEW

**Comment by simfeld** [comment]
Hi Daniel
Thanks a lot, I appreciate your help. I had a look through your commits, I think  I understand how it works now. So the way to proceed is:
- accept your PR
- add my name in the docs and commit
- the changes should then automatically appear in my own PR to the official dealii repository

right?

**Comment by masterleinad** [comment]
Yes, as soon as you merge this pull request dealii#4577 will be updated.
You would then add your name in another commit.

**Comment by simfeld** [comment]
Another question: What is the problem with the implementation for `FE_FaceP`? Is it because this class just works with basis functions and doesn't have support points?

**Comment by masterleinad** [comment]
Yes, if you look at the implementation for `FE_Q_Base` or `Face_FaceQ` you see that these identites are built using `unit_support_points` which is empty for `FE_FaceP`. In particular, we don't have any nodal interpolation available. Thus, the only case for which I know how to implement this easily is if both faces have the same polynomial degree. This implies that the polynomial degree is constant and there is no need to use a `hp::DoFHandler`at all.

**Comment by simfeld** [comment]
I have some more questions since it's my first pull request: What does it mean when you comment "/run-tests" in a dealii pull request? Is it now too late for me to adjust my real name as you suggested, or can I still do that? And what steps are missing for a successful merge?

**Comment by masterleinad** [comment]
> What does it mean when you comment "/run-tests" in a dealii pull request?

We use that `run-tests` command for automatically running some tests on a pull request.

> Is it now too late for me to adjust my real name as you suggested, or can I still do that?

No, until the pull request is merged it's not too late. Just push another commit that changes the file in `doc/news/changes/minor/20170711Simfeld-DanielArndt`.

> And what steps are missing for a successful merge?

We are just waiting for another developer to look at it again.

**Comment by simfeld** [comment]
@masterleinad regarding the issue of `FE_FaceP` having no `unit_support_points`: Is this merely a design decision or is there some mathematical reason for this? (ie would it be possible to write a different version of `FE_FaceP` using nodal interpolation?)

(should I be asking this in the dealii mailing lists or is it ok if I write you here?)

**Comment by masterleinad** [comment]
`FE_FaceP` is implemented base on `FE_DGP` which also does not define support_points.
It is just not clear how you would define these and interpolating by projecting is the next best thing to do.
Unfortunately, this is not compatible with the current design of `hp_*_indices`.

> (should I be asking this in the dealii mailing lists or is it ok if I write you here?)

It is better to ask these questions on the mailing list as much more people see it, i.e. more than just me.

**Pull request merged**
